language:
  scala
jdk:
- oraclejdk8
notifications:
  email:
  - bilalwahla@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
after_success:
- bash <(curl -s https://codecov.io/bash)